### PR TITLE
Changes bucket user type to String instead of Email

### LINKED ISSUE #40: bucket.user can not be populated
Changing the type to `String` will fix this, it looks like using mongoose doesn't know what to do with `mongoose.SchemaTypes.Email`, see: https://github.com/Storj/service-storage-models/blob/master/lib/models/bucket.js#L31

As mentioned in mongoose docs:

> Note: ObjectId, Number, String, and Buffer are valid for use as refs.
- http://mongoosejs.com/docs/populate.html

### PR DESCRIPTION
**Pull request by dylanlott**
Allows mongoose.populate() to work as expected

Should fix #40 

All unit tests passed.

### CODE REVIEW

**Comment by braydonf** [comment]
We may need to verify that the schema type wasn't being used for validation. And may be necessary to add basic validation in https://github.com/Storj/service-storage-models/blob/master/lib/models/user.js#L273

This may also fix? https://github.com/Storj/bridge/issues/301

**Comment by dylanlott** [comment]
I believe it should fix [Storj/bridge #301](https://github.com/Storj/bridge/issues/301), I think the email type provided by `mongoose.SchemaTypes.Email` doesn't have support for newer TLD's.

I agree, some validation in the `create` method would be in order. I can append that to this PR or create a new one. Front end / GUI validation is in place as well, but we should definitely have it in both places.

**Comment by braydonf** [comment]
The lengths are probably all that is needed to validate? *(since an email is sent to verify)*

```
<64 characters>@<255 characters>
```

As from: https://tools.ietf.org/html/rfc3696#page-6

**Comment by 161chihuahuas** [comment]
The schema type is being used for validation - hence the purpose of the schema types package in the first place. So, yes we must perform the validation ourselves now.

**Comment by dylanlott** [comment]
I'm working on a validation in the create method now.

**Comment by braydonf** [comment]
I don't know why coverage says it's decreasing, as the code added is covered.

**Comment by braydonf** [comment]
LGTM, went through and manually tested registration, and works as expected.

**Pull request merged**
