### PR TITLE
Coverage

### PR DESCRIPTION
**Pull request by barbaraliau**
Adding linting coverage with addition of `jshintrc` (taken from Storj/core) and add coveralls for test coverage.

### CODE REVIEW

**Comment by braydonf** [comment]
Looks good to me, w/ few nits:
- `package.json` build command isn't needed here
- `test/credit.unit.js` and `test/shard.unit.js` - `function` being on a new line for test definitions adds extra indentation. Maybe make the messages shorter? This is because of 80 column width?
- `frame.unit.js` For checking errors in tests, I've found that this, has given better error messages, when there is an error and shouldn't be:
```js
if (err) {
  return done(err);
}
```
- `lib/models/payment-processor-adapters/braintree.js` has commented code, but shouldn't be?

**Comment by barbaraliau** [comment]
Yes. 80 column width is normally super awesome...except test messages haha. I can look at making them shorter, or, just ignoring the line for jshint.

Ah. Didn't know that about errors. Will see how that works out.

I actually just commented that code to make jshint happy because they were unused variables. I'll just take it out for now.

**Comment by barbaraliau** [comment]
In regards to using `if (err) return done(err)`, this replaces `expect(err).to.not.be.an.instanceOf(Error);`? Or is in addition to?

**Comment by braydonf** [comment]
Yeah, it can replace.

**Comment by braydonf** [comment]
LGTM, going to go ahead and merge.

**Pull request merged**
